- hosts: all
  connection: local
  gather_facts: false
  collections:
    - arista.avd

  tasks:      
    - name: generate structured data
      import_role:
        name: arista.avd.eos_l3ls_evpn
      tags:
        - l3ls

    - name: generate intended configs to cli
      import_role:
        name: arista.avd.eos_cli_config_gen
      tags:
        - cli_gen

    - name: design
      import_role:
        name: arista.avd.eos_designs
      tags:
        - design

    - name: snapshot
      import_role:
        name: arista.avd.eos_snapshot
      tags:
        - snapshot

    - name: linter
      arista.eos.eos_config:
        src: "./intended/configs/{{ inventory_hostname}}.cfg"
        replace: config
      check_mode: yes
      tags:
        - linter

    - name: push with eapi
      arista.eos.eos_config:
        src: "./intended/configs/{{ inventory_hostname}}.cfg"
      tags:
        - eapi_push
  
    #- name: cvp
    #  import_role:
    #    name: eos_config_deploy_cvp
    #  tags:
    #    - cvp


    

    