  - hosts: all
    connection: local
    gather_facts: false
    collections:
      - arista.avd
    
    tasks:
      - name: generate intended configs to cli
        import_role:
          name: arista.avd.eos_cli_config_gen
    